version: "3"
services:
  amatsu-elastic-search:
    build: ./docker/elasticsearch
    ports:
      - 9200:9200
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
  amatsu-kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    ports:
      - "5601:5601"
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://amatsu-elastic-search:9200
    depends_on:
      - amatsu-elastic-search
